// ============================================================================
// Operation Financial Shadow — Evidence fixtures (canonical shape)
// ============================================================================

import { EvidenceSchema } from "@indago/contracts";
import type { Evidence } from "@indago/contracts";
import {
  CASE_ID,
  INVESTIGATION_ID,
  EVID_ACCOUNT_1,
  EVID_ACCOUNT_2,
  EVID_WIRE_1,
  EVID_WIRE_2,
  EVID_WIRE_3,
  EVID_EMAIL_1,
  EVID_EMAIL_2,
  EVID_REGISTRY,
  SRC_BANK_RECORDS,
  SRC_COMMS,
  SRC_REGISTRY,
  OBS_1,
  OBS_2,
  OBS_3,
  OBS_4,
  OBS_5,
  OBS_6,
  OBS_7,
  OBS_8,
  ENT_VICTOR,
  ENT_MARIA,
  ENT_SHELL_ONE,
  ENT_SHELL_TWO,
  ENT_BANK,
  ART_1,
  ART_2,
  HYP_1,
  HYP_2,
} from "./lookup";
import { obs, evt } from "./times";

const e1: Evidence = {
  id: EVID_ACCOUNT_1,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_BANK_RECORDS,
  type: "FINANCIAL",
  status: "VERIFIED",
  title: "Account 0092 — Transaction Ledger",
  description: "Ledger for shell company account 0092.",
  artifactIds: [ART_1],
  observationIds: [OBS_1],
  entityIds: [ENT_SHELL_ONE, ENT_SHELL_TWO],
  hypothesisIds: [HYP_1],
  strength: 0.78,
  posture: "T3_EVIDENCE_PACKAGE_CANDIDATE",
  provenance: { sourceId: SRC_BANK_RECORDS, extractor: "ledger.extractor.v1" },
  ingestionTime: { value: "2024-05-21T08:01:00.000Z", precision: "exact" },
  observedAt: evt("2023-12-15", "day"),
  createdAt: obs("2024-05-21"),
  updatedAt: obs("2024-05-21"),
};

const e2: Evidence = {
  id: EVID_ACCOUNT_2,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_BANK_RECORDS,
  type: "FINANCIAL",
  status: "VERIFIED",
  title: "Account 0093 — Transaction Ledger",
  description: "Ledger for intermediary account 0093.",
  artifactIds: [],
  observationIds: [OBS_2],
  entityIds: [ENT_BANK],
  hypothesisIds: [HYP_1],
  strength: 0.74,
  posture: "T3_EVIDENCE_PACKAGE_CANDIDATE",
  provenance: { sourceId: SRC_BANK_RECORDS, extractor: "ledger.extractor.v1" },
  ingestionTime: { value: "2024-05-21T08:02:00.000Z", precision: "exact" },
  observedAt: evt("2024-01-10", "day"),
  createdAt: obs("2024-05-21"),
  updatedAt: obs("2024-05-21"),
};

const e3: Evidence = {
  id: EVID_WIRE_1,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_BANK_RECORDS,
  type: "FINANCIAL",
  status: "PROCESSED",
  title: "Wire Transfer 2045",
  description: "Outbound wire: Shell One -> Account 0093.",
  artifactIds: [],
  observationIds: [OBS_3],
  entityIds: [ENT_SHELL_ONE, ENT_BANK],
  hypothesisIds: [HYP_1],
  strength: 0.68,
  posture: "T2_CORROBORATED_LEAD",
  provenance: { sourceId: SRC_BANK_RECORDS, extractor: "wire.extractor.v1" },
  ingestionTime: { value: "2024-05-21T08:03:00.000Z", precision: "exact" },
  observedAt: evt("2024-02-05", "day"),
  createdAt: obs("2024-05-21"),
  updatedAt: obs("2024-05-21"),
};

const e4: Evidence = {
  id: EVID_WIRE_2,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_BANK_RECORDS,
  type: "FINANCIAL",
  status: "PROCESSED",
  title: "Wire Transfer 2046",
  description: "Inbound wire into Shell Two from Account 0093.",
  artifactIds: [],
  observationIds: [OBS_4],
  entityIds: [ENT_SHELL_TWO, ENT_BANK],
  hypothesisIds: [HYP_1],
  strength: 0.66,
  posture: "T2_CORROBORATED_LEAD",
  provenance: { sourceId: SRC_BANK_RECORDS, extractor: "wire.extractor.v1" },
  ingestionTime: { value: "2024-05-21T08:04:00.000Z", precision: "exact" },
  observedAt: evt("2024-02-06", "day"),
  createdAt: obs("2024-05-21"),
  updatedAt: obs("2024-05-21"),
};

const e5: Evidence = {
  id: EVID_WIRE_3,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_BANK_RECORDS,
  type: "FINANCIAL",
  status: "PROCESSED",
  title: "Wire Transfer 2077",
  description: "Disbursement from Shell Two to third-party vendor.",
  artifactIds: [],
  observationIds: [OBS_5],
  entityIds: [ENT_SHELL_TWO],
  hypothesisIds: [HYP_2],
  strength: 0.55,
  posture: "T1_INVESTIGATIVE_LEAD",
  provenance: { sourceId: SRC_BANK_RECORDS, extractor: "wire.extractor.v1" },
  ingestionTime: { value: "2024-05-21T08:05:00.000Z", precision: "exact" },
  observedAt: evt("2024-03-18", "day"),
  createdAt: obs("2024-05-21"),
  updatedAt: obs("2024-05-21"),
};

const e6: Evidence = {
  id: EVID_EMAIL_1,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_COMMS,
  type: "COMMUNICATION",
  status: "PROCESSED",
  title: "Email Thread 118 — Invoice Routing",
  description: "Correspondence authorizing invoice routing between shells.",
  artifactIds: [ART_2],
  observationIds: [OBS_6],
  entityIds: [ENT_VICTOR, ENT_MARIA],
  hypothesisIds: [HYP_1],
  strength: 0.6,
  posture: "T2_CORROBORATED_LEAD",
  provenance: { sourceId: SRC_COMMS, extractor: "mail.extractor.v1" },
  ingestionTime: { value: "2024-05-22T09:05:00.000Z", precision: "exact" },
  observedAt: evt("2023-12-20", "day"),
  createdAt: obs("2024-05-22"),
  updatedAt: obs("2024-05-22"),
};

const e7: Evidence = {
  id: EVID_EMAIL_2,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_COMMS,
  type: "COMMUNICATION",
  status: "PROCESSED",
  title: "Email Thread 130 — Signing Authority",
  description: "Message confirming signing authority for account 0093.",
  artifactIds: [],
  observationIds: [OBS_7],
  entityIds: [ENT_MARIA, ENT_BANK],
  hypothesisIds: [HYP_2],
  strength: 0.58,
  posture: "T1_INVESTIGATIVE_LEAD",
  provenance: { sourceId: SRC_COMMS, extractor: "mail.extractor.v1" },
  ingestionTime: { value: "2024-05-22T09:07:00.000Z", precision: "exact" },
  observedAt: evt("2024-01-22", "day"),
  createdAt: obs("2024-05-22"),
  updatedAt: obs("2024-05-22"),
};

const e8: Evidence = {
  id: EVID_REGISTRY,
  caseId: CASE_ID,
  investigationId: INVESTIGATION_ID,
  sourceId: SRC_REGISTRY,
  type: "RECORD",
  status: "UNDER_REVIEW",
  title: "Registry Filing — Shell One Incorporation",
  description: "Corporate registry filing with listed nominee director.",
  artifactIds: [],
  observationIds: [OBS_8],
  entityIds: [ENT_SHELL_ONE, ENT_VICTOR],
  hypothesisIds: [HYP_1],
  strength: 0.8,
  posture: "T3_EVIDENCE_PACKAGE_CANDIDATE",
  provenance: { sourceId: SRC_REGISTRY, extractor: "registry.extractor.v1" },
  ingestionTime: { value: "2024-05-23T10:01:00.000Z", precision: "exact" },
  observedAt: evt("2023-11-05", "day"),
  createdAt: obs("2024-05-23"),
  updatedAt: obs("2024-05-23"),
};

/** Canonical parsed evidence set. */
export const operationFinancialShadowEvidence: Evidence[] = [
  EvidenceSchema.parse(e1),
  EvidenceSchema.parse(e2),
  EvidenceSchema.parse(e3),
  EvidenceSchema.parse(e4),
  EvidenceSchema.parse(e5),
  EvidenceSchema.parse(e6),
  EvidenceSchema.parse(e7),
  EvidenceSchema.parse(e8),
];
