// ============================================================================
// Operation Financial Shadow — Graph fixtures (canonical shape)
// ============================================================================

import {
  GraphVersionSchema,
  GraphNodeSchema,
  GraphEdgeSchema,
} from "@indago/contracts";
import type { GraphVersion, GraphNode, GraphEdge } from "@indago/contracts";
import {
  GRAPH_VERSION,
  INVESTIGATION_ID,
  GN_VICTOR,
  GN_MARIA,
  GN_SHELL_ONE,
  GN_SHELL_TWO,
  GN_BANK,
  GN_WITNESS,
  GE_1,
  GE_2,
  GE_3,
  GE_4,
  GE_5,
  GE_6,
  REL_1,
  REL_2,
  REL_3,
  REL_4,
  REL_5,
  REL_6,
  ENT_VICTOR,
  ENT_MARIA,
  ENT_SHELL_ONE,
  ENT_SHELL_TWO,
  ENT_BANK,
  ENT_WITNESS,
} from "./lookup";
import { obs } from "./times";

const versionData: GraphVersion = {
  id: GRAPH_VERSION,
  investigationId: INVESTIGATION_ID,
  versionNumber: 3,
  status: "ACTIVE",
  projectionStatus: "COMPLETE",
  nodeCount: 6,
  edgeCount: 6,
  createdAt: obs("2024-06-15"),
  updatedAt: obs("2024-06-28"),
};

const nodes: GraphNode[] = [
  {
    id: GN_VICTOR,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    type: "ENTITY",
    entityId: ENT_VICTOR,
    label: "Victor Aldridge",
    structuralImportance: 0.9,
    observationCount: 2,
    sourceCount: 2,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GN_MARIA,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    type: "ENTITY",
    entityId: ENT_MARIA,
    label: "Maria Castellan",
    structuralImportance: 0.68,
    observationCount: 2,
    sourceCount: 1,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GN_SHELL_ONE,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    type: "ENTITY",
    entityId: ENT_SHELL_ONE,
    label: "Aldridge Holdings S.A.",
    structuralImportance: 0.85,
    observationCount: 3,
    sourceCount: 2,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GN_SHELL_TWO,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    type: "ENTITY",
    entityId: ENT_SHELL_TWO,
    label: "Northbridge Capital Ltd.",
    structuralImportance: 0.8,
    observationCount: 3,
    sourceCount: 2,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GN_BANK,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    type: "ENTITY",
    entityId: ENT_BANK,
    label: "Intermediary Account 0093",
    structuralImportance: 0.95,
    observationCount: 4,
    sourceCount: 2,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GN_WITNESS,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    type: "ENTITY",
    entityId: ENT_WITNESS,
    label: "Unidentified Witness",
    structuralImportance: 0.2,
    observationCount: 0,
    sourceCount: 0,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
];

const edges: GraphEdge[] = [
  {
    id: GE_1,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    sourceNodeId: GN_VICTOR,
    targetNodeId: GN_SHELL_ONE,
    relationType: "ownership",
    relationHypothesisId: REL_1,
    support: 0.78,
    structuralImportance: 0.72,
    directed: true,
    status: "ACTIVE",
    observationCount: 1,
    sourceCount: 1,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GE_2,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    sourceNodeId: GN_MARIA,
    targetNodeId: GN_BANK,
    relationType: "financial",
    relationHypothesisId: REL_2,
    support: 0.66,
    structuralImportance: 0.6,
    directed: true,
    status: "ACTIVE",
    observationCount: 1,
    sourceCount: 1,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GE_3,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    sourceNodeId: GN_SHELL_ONE,
    targetNodeId: GN_BANK,
    relationType: "financial",
    relationHypothesisId: REL_3,
    support: 0.74,
    structuralImportance: 0.68,
    directed: true,
    temporalRange: {
      validFrom: { value: "2024-02-05T12:00:00.000Z", precision: "exact" },
      validTo: { value: "2024-02-05T12:00:00.000Z", precision: "exact" },
      precision: "exact",
      semantics: "observed",
    },
    status: "ACTIVE",
    observationCount: 2,
    sourceCount: 1,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GE_4,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    sourceNodeId: GN_BANK,
    targetNodeId: GN_SHELL_TWO,
    relationType: "financial",
    relationHypothesisId: REL_4,
    support: 0.72,
    structuralImportance: 0.66,
    directed: true,
    status: "ACTIVE",
    observationCount: 2,
    sourceCount: 1,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GE_5,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    sourceNodeId: GN_SHELL_ONE,
    targetNodeId: GN_SHELL_TWO,
    relationType: "financial",
    relationHypothesisId: REL_5,
    support: 0.7,
    structuralImportance: 0.64,
    directed: true,
    status: "ACTIVE",
    observationCount: 2,
    sourceCount: 1,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
  {
    id: GE_6,
    investigationId: INVESTIGATION_ID,
    versionId: GRAPH_VERSION,
    sourceNodeId: GN_VICTOR,
    targetNodeId: GN_SHELL_TWO,
    relationType: "ownership",
    relationHypothesisId: REL_6,
    support: 0.58,
    structuralImportance: 0.5,
    directed: true,
    status: "ACTIVE",
    observationCount: 1,
    sourceCount: 1,
    createdAt: obs("2024-06-15"),
    updatedAt: obs("2024-06-15"),
  },
];

/** Canonical parsed graph fixtures. */
export const operationFinancialShadowGraph = {
  version: GraphVersionSchema.parse(versionData),
  nodes: nodes.map((n) => GraphNodeSchema.parse(n)),
  edges: edges.map((e) => GraphEdgeSchema.parse(e)),
};
